# Generated by Django 4.0.3 on 2026-03-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: Maximum number of participants allowed for this event.', null=True),
        ),
    ]
